config/routes.rb
Pfm::Application.routes.draw do

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  devise_for :users do
    get "/" => "devise/registrations#new", :as => :new_user_registration
  end

  resources :users, :only => [:show, :edit, :update]
  resources :acumen_tests

  resources :accounts do
    collection do
      get :list
    end
  end

  resources :budgets

  resources :goals do
    collection do
      get :select
    end
  end

  resources :transactions
  resources :trends, :only => :index

  match '/home' => 'pages#show', :id => 'home'
  match '/about' => 'pages#show', :id => 'about'
  match '/how_it_works' => 'pages#show', :id => 'how_it_works'
  match '/faq' => 'pages#show', :id => 'faq'
  match '/terms_of_use' => 'pages#show', :id => 'terms_of_use'
  match '/help_create_account' => 'pages#show', :id => 'help_create_account'
  match '/dashboard' => 'dashboard#show'
  match '/sundry_legal_information' => 'pages#show', :id => 'sundry_legal_information'
  match '/privacy_security_policy' => 'pages#show', :id => 'privacy_security_policy'
  match '/community_policy' => 'pages#show', :id => 'community_policy'
  match '/pricing' => 'pages#show', :id => 'pricing'
  

  resource :contact_us, :only => [:create]
  match '/contact_us' => 'contact_us#new'

  root to: 'pages#home'

end

app/models/budget.rb
class Budget < ActiveRecord::Base
  acts_as_taggable
  attr_accessible :category, :amount, :period, :start, :user_id, :tag_list, :budget_type
  belongs_to :user
  belongs_to :category
  
  validates :category, :amount, :period, :budget_type, :presence => true
  validates :amount, :period, :numericality => true
  validates :budget_type, :inclusion => { :in => %w(income spending) }

  scope :income, where(:budget_type => 'income')
  scope :spending, where(:budget_type => 'spending')
  scope :in_this_month, where('created_at >= ?', Date.today.beginning_of_month)
  
  
  def self.search(start_date, end_date)
    if start_date && !(start_date == '')
      end_date == '' ? end_date = Time.zone.now : end_date
      where('created_at >= ? AND created_at <= ?', start_date, end_date.to_date + 1.day)
    else
      in_this_month
    end
  end
end

app/controllers/budgets_controller.rb
class BudgetsController < ApplicationController
  before_filter :authenticate_user!
  
  layout Proc.new { |controller| controller.request.xhr? ? 'popup' : 'application' }

  def index
    @title = 'Budgets - Budget 24/7'
    # @budget = Budget.new(:budget_type => 'income')
    @budgets =  current_user.budgets.search(params[:budgets_start], params[:budgets_end])

    respond_to do |format|
      format.html
      format.js
      format.json { render :json => @budgets }
    end
  end

  def show
    @budget = Budget.find(params[:id])

    respond_to do |format|
      format.html
      format.json { render :json => @budget }
    end
  end

  def new
    @budget = Budget.new(budget_type: params[:budget_type])
    
    respond_to do |format|
      format.html
      format.json { render :json => @budget }
    end
  end

  def edit
    @budget = Budget.find(params[:id])
  end

  def create
    @budget = current_user.budgets.build params[:budget]
    
    @budget.amount = -@budget.amount if @budget.budget_type == 'spending'
    
    respond_to do |format|
      if @budget.save
        format.html { redirect_to budgets_path(budget_type: @budget.budget_type), :notice => 'Budget was successfully created.' }
        format.json { render :json => @budget, :status => :created, :location => @budget }
      else
        format.html { render :action => "new" }
        format.json { render :json => @budget.errors, :status => :unprocessable_entity }
      end
    end
  end

  def update
    @budget = Budget.find(params[:id])

    respond_to do |format|
      if @budget.update_attributes(params[:budget])
        format.html { redirect_to budgets_path, :notice => 'Budget was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @budget.errors, :status => :unprocessable_entity }
      end
    end
  end

  def destroy
    @budget = Budget.find(params[:id])
    @budget.destroy

    respond_to do |format|
      format.html { redirect_to budgets_url }
      format.json { head :ok }
    end
  end
end

app/helpers/budgets_helper.rb
module BudgetsHelper
  def period_select
    %w(2 3 4 5 6 7 8 9 10 11 12).collect{ |p| [pluralize(p, "month"), p] }
  end
end

app/views/budgets/_budgets.html.haml
%h2.title Income
%span.sub_title 
  ₦ 5,500 so far of ₦ 
  = @budgets.income.map(&:amount).sum
%a.add-new{:onClick => "show_overlay('new-budget');", :style => "text-align:left;"}
  %span>
  Create a new income
#income
  - @budgets.income.each do |income|
    %ul
      %li.b_title
        Income:
        %span.b-categ= income.category.name
      %li.do_edit_list
        %a.do_edit{:href => "#", :onClick => "show_overlay('pop-up-edit');"}
      %li.rate_value 
        ₦ 
        = income.amount
        of 
        ₦ 
        = @budgets.income.map(&:amount).sum
      %li.progress-bar
        %span.positive-progress{:style => "width:36%;"}
#spending
  %h2.title Spending
  %span.sub_title 
    ₦ 900 spent of ₦ 
    = @budgets.spending.map(&:amount).sum
  %a.add-new{:href => "#", :onClick => "show_overlay('new-budget');", :style => "text-align:left;"}
    %span>
    Create a new budget
  - @budgets.spending.each do |spending|
    %ul
      %li.b_title
        Spending:
        %span.b-categ= spending.category.name
      %li.do_edit_list
        %a.do_edit{:href => "#", :onClick => "show_overlay('pop-up-edit');"}
        %li.rate_value 
          ₦ 
          = spending.amount
          of 
          ₦ 
          = @budgets.spending.map(&:amount).sum
      %li.progress-bar
        %span.negative-progress{:style => "width:96%;"}

app/views/budgets/_form.html.erb
<%= simple_form_for @budget, :validate => true do |f| %>
  <%= render 'shared/error_messages', :object => f.object %>
  <%= f.input :budget_type, :as => 'hidden' %>
  <%= f.input :category, :collection => Category.send(@budget.budget_type) %>

  <div class="field radios">
    <p>When will this happen?</p>

    <div class="radiogroup">
      <%= radio_button_tag "period", "monthly" %>
      <%= label_tag "period_monthly", "Every month" %>

      <%= radio_button_tag "period", "few_month" %>
      <%= label_tag "period_few_month", "Every few month" %>

      <%= radio_button_tag "period", "once", true %>
      <%= label_tag "period_once", "Once" %>
    </div>
  </div>

  <%= f.input :amount %>
  <%= f.input :tag_list %>
  <div class="period hidden">
    every <%= select_tag :period, options_for_select(period_select, @budget.period) %>
  </div>
  <div class="start">
    <% if !@budget.new_record? && !@budget.start.nil? %>
      <div class="hidden" id="budget_year"><%= @budget.start.year %></div>
      <div class="hidden" id="budget_month"><%= @budget.start.month %></div>
    <% end %>
    My next is in <%= f.date_select :start, :use_short_month => true,
                                            :discard_day => true,
                                            :start_year => Time.now.year %>
  </div>
  <div class="field hidden"><%= f.text_field :period %></div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/budgets/_incomes.html.erb
<div id="incomes">
  <h3>Income</h3>
  <div class="amount">
    <div class="sum">
      <div class="cur">&#8358;</div><%= current_user.transactions_sum_by_category("Income") %>
    </div>
    so far of
    <div class="sum">
      <div class="cur">&#8358;</div><%= @income_budgets.map(&:amount).sum %>
    </div>
  </div>

  <%= link_to 'Create a new income', new_budget_path(:budget_type => 'income'), :data => {:toggle => 'modal', :target => '#new_budget-modal'}, :class => "new-budget add_new", :title => "New budget" %>
  <div id="new_budget-modal" class="modal" style="display:none">
    <div class="modal-body">
      <p>Loading…</p>
    </div>
  </div>
  <% if @income_budgets.any? %>
    <div id="incomes-list">
      <% @income_budgets.each do |income| %>
        <div class="income item">
          <%= income.category.name %> <%= link_to "edit", edit_budget_path(income), :class => "edit" %>
          <div class="spent">
            <div class="b-start">
              &#8358;<div class="start"><%= current_user.transactions_sum_by_category("Income") %></div>
            </div> &nbsp;&nbsp;of&nbsp;&nbsp;
            <div class="b-end">
              &#8358;<div class="end"><%= @income_budgets.map(&:amount).sum %></div>
            </div>
          </div>
          <div class="progress"></div>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/budgets/_spending.html.erb
<script type='text/javascript'>(function () {
    function loadWebreep() {
        var s = document.createElement('script');
        s.type = 'text/javascript';
        s.async = true;
        s.src = 'https://api.webreep.com/Feedback/Get/3508ed12-7cf5-472d-87cb-215421267d77';
        var x = document.getElementsByTagName('script')[0];
        x.parentNode.insertBefore(s, x);
    }

    if (window.attachEvent) {
        window.attachEvent('onload', loadWebreep);
    } else {
        window.addEventListener('load', loadWebreep, false);
    }
})();</script>
<div id="spending">
  <h3>Spending</h3>

  <div class="amount">
    &#8358; <%= current_user.spending_amount %> spent of
    &#8358; <%= @spending_budgets.map(&:amount).sum %>
  </div>

  <%= link_to "Create a new budget", new_budget_path(:budget_type => 'spending'), :class => "new-budget" %>

  <% if @spending_budgets.any? %>
      <div id="spending-list">
        <% @spending_budgets.each do |spending| %>
            <div class="spending item">
              <%= spending.category.name %>
              <%= link_to "edit", edit_budget_path(spending, :category => spending.category), :class => "edit" %>
              <div class="spent">
                <div class="b-start">
                  &#8358;
                  <div class="start"><%= current_user.transactions_sum_by_category(spending.category) %></div>
                </div>
                &nbsp;&nbsp;of&nbsp;&nbsp;
                <div class="b-end">
                  &#8358;
                  <div class="end"><%= spending.amount %></div>
                </div>
              </div>
              <div class="progress"></div>
            </div>
        <% end %>
      </div>
  <% end %>
</div>

app/views/budgets/edit.html.erb
<h1>Editing budget</h1>

<%= render 'form' %>

<%= link_to 'Show', @budget %>

app/views/budgets/index.html.haml
#content.grid_24
  %h2.page-title
    Life Budgets
    %sup TM
  / Right Content
  #right-content.grid_17.full-c
    %h3.content-title November - December, 2012
    
    #budget-header
      .budgets_calendar
        .budgets-months
        .predefined
          = link_to "This month", '#', :id => "timeline_one_month"
          = link_to "Last month", '#', :id => "timeline_last_month"
          = link_to "This year", '#', :id => "timeline_year"
          = link_to "All time", '#', :id => "timeline_all"
        #calendar
          #budgets_timeline
          %br/
          = form_tag budgets_path, :method => "get", :id => "budgets_search", :class => "hidden" do
            = text_field_tag :budgets_start, params[:budgets_start]
            = text_field_tag :budgets_end, params[:budgets_end]
            = submit_tag "Search", :id => "budgets_search"
    / Budget Right Content
    #budget-content-right.grid_17
      = render :partial => 'budgets'
    / End Budget Right Content
    / Left Content
    #left-content
      #budget-details.grid_6
        %h2.title You’ve budgeted
        %ul
          %ul
            %li.sub_title Income, ₦
            %li.do_count.positive= @budgets.income.map(&:amount).sum
          %ul
            %li.sub_title Spending, ₦
            %li.do_count.negative= @budgets.spending.map(&:amount).sum
          %ul
            %li.sub_title Goals, ₦
            %li.do_count 0
          %ul
            %li.sub_title Left Over, ₦
            %li.do_count.positive= (@budgets.income.map(&:amount).sum + @budgets.spending.map(&:amount).sum)
    / End Left Content
  / End Right Content
/ End Content

app/views/budgets/index.js.erb
$("#budget-content-right").html("<%= escape_javascript(render :partial => "budgets") %>");

$('#create_new_budget').dialog({
  autoOpen: false,
  resizable: false,
  modal: true,
  minWidth: 490,
  dialogClass: 'my_dialog',
  title: "New budget",
  buttons: {
    'Save': function() {
      $('#new_budget').submit()
      $(this).dialog('close')
    },
    'Cancel': function() {
      $(this).dialog('close')
    }
  }
})

$('#result').progressBar();

app/views/budgets/new.html.erb
<div class="block">
  <h1>New budget</h1>
  <%= render 'form' %>

  <%= link_to 'Back', budgets_path %>
</div>

app/views/budgets/show.html.erb
<h1>Budget</h1>

<p>
  <b>Category:</b>
  <%= @budget.category %>
</p>

<p>
  <b>Amount:</b>
  <%= @budget.amount %>
</p>

<p>
  <b>Period:</b>
  <%= @budget.period %>
</p>

<% if @budget.start %>
  <p>
    <b>Started at:</b>
    <%=l @budget.start, :format => :short %>
  </p>
<% end %>


<%= link_to 'Edit', edit_budget_path(@budget) %> |
<%= link_to 'Back', list_budgets_path %>