config/routes.rb
Pfm::Application.routes.draw do

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  devise_for :users do
    get "/" => "devise/registrations#new", :as => :new_user_registration
  end

  resources :users, :only => [:show, :edit, :update]
  resources :acumen_tests

  resources :accounts do
    collection do
      get :list
    end
  end

  resources :budgets

  resources :goals do
    collection do
      get :select
    end
  end

  resources :transactions
  resources :trends, :only => :index

  match '/home' => 'pages#show', :id => 'home'
  match '/about' => 'pages#show', :id => 'about'
  match '/how_it_works' => 'pages#show', :id => 'how_it_works'
  match '/faq' => 'pages#show', :id => 'faq'
  match '/terms_of_use' => 'pages#show', :id => 'terms_of_use'
  match '/help_create_account' => 'pages#show', :id => 'help_create_account'
  match '/dashboard' => 'dashboard#show'
  match '/sundry_legal_information' => 'pages#show', :id => 'sundry_legal_information'
  match '/privacy_security_policy' => 'pages#show', :id => 'privacy_security_policy'
  match '/community_policy' => 'pages#show', :id => 'community_policy'
  match '/pricing' => 'pages#show', :id => 'pricing'
  

  resource :contact_us, :only => [:create]
  match '/contact_us' => 'contact_us#new'

  root to: 'pages#home'

end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(object.errors.count, "error") %>
      prohibited this <%= object.class.to_s.underscore.humanize.downcase %>
      from being saving:</h2>
    <p>There were a problem with the following fields:</p>
    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<menu>
  <ul>
    <li class="head">About us</li>
    <li><%= link_to "How it works", how_it_works_path %></li>
    <!-- <li><%#= link_to "What is Budget 24-7", '#' %></li> -->
    <li><%= link_to "Who we are", about_path %></li>
  </ul>

  <ul>
    <li class="head">Support</li>
    <!-- <li><%#= link_to "Help center", '#' %></li>
    <li><%#= link_to "Privacy & Terms", '#' %></li>
    <li><%#= link_to "Copyright", '#' %></li> -->
    <li><%= link_to "Contact us", contact_us_path %></li>
  </ul>

  <ul>
    <li class="head">Policies</li>
    <!-- <li><%#= link_to "Privacy Policy", '#' %></li>
    <li><%#= link_to "Security Policy", '#' %></li> -->
    <li><%= link_to "Terms of use", terms_of_use_path %></li>
  </ul>

  <ul>
    <li class="head">Community</li>
    <li><%= link_to "Blog", 'http://budget247.wordpress.com' %></li>
    <!-- <li><%#= link_to "Live surveys", '#' %></li>
    <li><%#= link_to "Competitions", '#' %></li>
    <li><%#= link_to "Events", '#' %></li>
    <li><%#= link_to "Videos", '#' %></li> -->
  </ul>

  <div class="content">
    <%= image_tag "logo_footer.png", :title => "Budget 24-7" %>

    <p>
      Plan your finances. Socially
    </p>

    <p class="copy">©2012 Budget 24-7, Inc.</p>
  </div>
</menu>

app/views/shared/_menu.html.haml
- if user_signed_in?
  %li= link_to "Dashboard", dashboard_path, class: current_page_menu('dashboard')
  %li= link_to "Accounts", accounts_path, class: current_page_menu('accounts')
  %li= link_to "Budgets", budgets_path, class: current_page_menu('budgets')
  %li= link_to "Goals", goals_path, class: current_page_menu('goals')
  %li= link_to "Trends", trends_path, class: current_page_menu('trends')
  %li= link_to "Community", 'http://community.budget247.com'
  %li= link_to "Profile", current_user, class: current_page_menu('users')
  %li= link_to "Sign out", destroy_user_session_path, method: :delete, class: 'sign_out'

- else
  %li.r-border
    = link_to 'Sign In', new_user_session_path
  %li
    = link_to 'Sign Up', '#'