config/routes.rb
Pfm::Application.routes.draw do

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  devise_for :users do
    get "/" => "devise/registrations#new", :as => :new_user_registration
  end

  resources :users, :only => [:show, :edit, :update]
  resources :acumen_tests

  resources :accounts do
    collection do
      get :list
    end
  end

  resources :budgets

  resources :goals do
    collection do
      get :select
    end
  end

  resources :transactions
  resources :trends, :only => :index

  match '/home' => 'pages#show', :id => 'home'
  match '/about' => 'pages#show', :id => 'about'
  match '/how_it_works' => 'pages#show', :id => 'how_it_works'
  match '/faq' => 'pages#show', :id => 'faq'
  match '/terms_of_use' => 'pages#show', :id => 'terms_of_use'
  match '/help_create_account' => 'pages#show', :id => 'help_create_account'
  match '/dashboard' => 'dashboard#show'
  match '/sundry_legal_information' => 'pages#show', :id => 'sundry_legal_information'
  match '/privacy_security_policy' => 'pages#show', :id => 'privacy_security_policy'
  match '/community_policy' => 'pages#show', :id => 'community_policy'
  match '/pricing' => 'pages#show', :id => 'pricing'
  

  resource :contact_us, :only => [:create]
  match '/contact_us' => 'contact_us#new'

  root to: 'pages#home'

end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_filter :authenticate_user!
  before_filter :find_account

  def index
    @transactions = Transaction.all

    respond_to do |format|
      format.html
      format.json { render :json => @transactions }
      format.csv { export_to_csv }
    end
  end

  def show
    @transaction = Transaction.find(params[:id])

    respond_to do |format|
      format.html
      format.json { render :json => @transaction }
    end
  end

  def new
    @transaction = Transaction.new
    respond_to do |format|
      format.html
      format.json { render :json => @transaction }
    end
  end

  def edit
    @transaction = Transaction.find(params[:id])
    @accounts = current_user.accounts.all
  end

  def create
    @transaction = current_user.transactions.build(params[:transaction])
    respond_to do |format|
      if @transaction.save
        format.html do
          if budget_by_transaction(@transaction) && transaction_higher_budget?(@transaction)
            UserMailer.budget_exceed(current_user, @budget).deliver
            redirect_to @transaction,
                        :notice => 'Transaction was successfully created.',
                        :alert => "Your budget with '#{@transaction.category}' category is exceeded."
          else
            redirect_to @transaction, :notice => 'Transaction was successfully created.'
          end
        end
        format.json { render :json => @transaction, :status => :created, :location => @transaction }
      else
        format.html { render :new }
        format.json { render :json => @transaction.errors, :status => :unprocessable_entity }
      end
    end
  end

  def update
    @transaction = Transaction.find(params[:id])

    respond_to do |format|
      if @transaction.update_attributes(params[:transaction])
        format.html do
          if budget_by_transaction(@transaction) && transaction_higher_budget?(@transaction)
            UserMailer.budget_exceed(current_user, @budget).deliver
            redirect_to @transaction,
                        :notice => 'Transaction was successfully updated.',
                        :alert => "Your budget with '#{@transaction.category}' category is exceeded."
          else
            redirect_to @transaction, :notice => 'Transaction was successfully updated.'
         end
        end
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @transaction.errors, :status => :unprocessable_entity }
      end
    end
  end

  def destroy
    @transaction = Transaction.find(params[:id])
    @transaction.destroy

    respond_to do |format|
      format.html { redirect_to transactions_url }
      format.json { head :ok }
    end
  end

  private

  def find_account
    redirect_to new_account_path unless current_user.accounts.any?
  end

  def budget_by_transaction(transaction)
    @budget = current_user.budgets.find_by_category(transaction.category)
  end

  def transaction_higher_budget?(transaction)
    if budget_by_transaction(transaction)
      budget_by_transaction(transaction).amount < transaction.amount
    end
  end

  protected

  def export_to_csv
    @transactions = Transaction.find(:all, :order => "category ASC")
    @outfile = "transactions_" + I18n.l(Time.now, :format => :short) + ".csv"
    csv_data = FasterCSV.generate(:force_quotes  => true) do |csv|
      csv << [
        "Category",
        "Amount",
        "Created",
        "Description",
        "Note"
      ]
      @transactions.each do |transaction|
        csv << [
          transaction.category,
          transaction.amount,
          transaction.created_at,
          transaction.description,
          transaction.note
        ]
      end
    end

    send_data csv_data, :type => 'text/csv; charset=utf-8;'
  end
end

app/helpers/transactions_helper.rb
module TransactionsHelper
  def percentage(amount)
    (sprintf("%.3f", amount).to_f * 100)
  end

  def transactions_categories(transactions)
    transactions.map{ |transaction| transaction.category }.uniq
  end

  def transactions_months(transactions)
    transactions.map{ |transaction| transaction.created_at.month }.uniq.sort
  end

  def transactions_descriptions(transactions)
    transactions.map{ |transaction| transaction.description }.uniq.sort
  end

  def categorized(transactions)
    categorized_transactions = []
    (transactions_categories(transactions)).each do |category|
      categorized_transactions << [category, transactions.find_all{|tr| tr.category == category}.map(&:amount).sum.to_f]
    end
    categorized_transactions = Hash[*categorized_transactions.flatten!]
  end

  def monthly(transactions)
    monthly_transactions = []
    (transactions_months(transactions)).each do |month|
      monthly_transactions << [month, transactions.find_all{ |tr| tr.created_at.month == month}.map(&:amount).sum.to_f]
    end
    monthly_transactions = Hash[*monthly_transactions.flatten!]
  end

  def merchanized(transactions)
    merchanized_transactions = []
    (transactions_descriptions(transactions)).each do |description|
      merchanized_transactions << [description, transactions.find_all{ |tr| tr.description == description }.map(&:amount).sum.to_f]
    end
    merchanized_transactions = Hash[*merchanized_transactions.flatten!]
  end
end

app/views/transactions/_form.html.erb
<%= form_for(@transaction) do |f| %>
  <%= render 'shared/error_messages', :object => f.object %>

  <div class="field">
    <%= f.label :category %><br />
    <%= f.select :category, Transaction::CATEGORIES %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description, :rows => 5 %>
  </div>
  <div class="field">
    <%= f.label :amount %><br />
    <%= f.text_field :amount %>
  </div>
  <div class="field">
    <%= f.label :note %><br />
    <%= f.text_area :note, :rows => 5 %>
  </div>
  <div class="field">
    <%= f.label :account_id, "Account" %><br />
    <%= f.select :account_id, current_user.accounts.all.collect{ |a| [a.name, a.id] }, { :include_blank => true } %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/transactions/edit.html.erb
<h1>Editing transaction</h1>

<%= render 'form' %>

<%= link_to 'Show', @transaction %> |
<%= link_to 'Back', transactions_path %>

app/views/transactions/index.html.erb
<h1>Listing transactions</h1>

<div class="block">
  <table>
    <tr>
      <th>Category</th>
      <th>Description</th>
      <th>Amount</th>
      <th>Note</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>

  <% @transactions.each do |transaction| %>
    <tr>
      <td><%= transaction.category %></td>
      <td><%= transaction.description %></td>
      <td><%= transaction.amount %></td>
      <td><%= transaction.note %></td>
      <td><%= link_to 'Show', transaction %></td>
      <td><%= link_to 'Edit', edit_transaction_path(transaction) %></td>
      <td><%= link_to 'Destroy', transaction, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
  </table>

  <br />

  <%= link_to 'New Transaction', new_transaction_path %>
  <br />
  <%= link_to "Export to CSV", request.parameters.merge({:format => :csv}) %>
</div>

app/views/transactions/new.html.erb
<h1>New transaction</h1>

<%= render 'form' %>

<%= link_to 'Back', transactions_path %>

app/views/transactions/show.html.erb
<div class="block">
  <p>
    <b>Category:</b>
    <%= @transaction.category %>
  </p>

  <p>
    <b>Description:</b>
    <%= @transaction.description %>
  </p>

  <p>
    <b>Amount:</b>
    <%= @transaction.amount %>
  </p>

  <p>
    <b>Note:</b>
    <%= @transaction.note %>
  </p>


  <%= link_to 'Edit', edit_transaction_path(@transaction) %> |
  <%= link_to 'Back', transactions_path %>
</div>