config/routes.rb
Pfm::Application.routes.draw do

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  devise_for :users do
    get "/" => "devise/registrations#new", :as => :new_user_registration
  end

  resources :users, :only => [:show, :edit, :update]
  resources :acumen_tests

  resources :accounts do
    collection do
      get :list
    end
  end

  resources :budgets

  resources :goals do
    collection do
      get :select
    end
  end

  resources :transactions
  resources :trends, :only => :index

  match '/home' => 'pages#show', :id => 'home'
  match '/about' => 'pages#show', :id => 'about'
  match '/how_it_works' => 'pages#show', :id => 'how_it_works'
  match '/faq' => 'pages#show', :id => 'faq'
  match '/terms_of_use' => 'pages#show', :id => 'terms_of_use'
  match '/help_create_account' => 'pages#show', :id => 'help_create_account'
  match '/dashboard' => 'dashboard#show'
  match '/sundry_legal_information' => 'pages#show', :id => 'sundry_legal_information'
  match '/privacy_security_policy' => 'pages#show', :id => 'privacy_security_policy'
  match '/community_policy' => 'pages#show', :id => 'community_policy'
  match '/pricing' => 'pages#show', :id => 'pricing'
  

  resource :contact_us, :only => [:create]
  match '/contact_us' => 'contact_us#new'

  root to: 'pages#home'

end

app/models/account.rb
class Account < ActiveRecord::Base
  ACCOUNT_STATUSES = ['active', 'inactive']

  attr_accessible :name, :status, :bank_id, :user_id, :amount, :transactions_attributes

  validates :name, :status, :presence => true
  validates :status, :inclusion => { :in => ACCOUNT_STATUSES }

  belongs_to :user
  has_one :bank
  has_many :transactions
  has_and_belongs_to_many :goals

  accepts_nested_attributes_for :transactions
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_filter :authenticate_user!
  helper_method :sort_column, :sort_direction

  def index
    @title = 'Accounts - Budget 24/7'
    @accounts = current_user.accounts.all
    @income_amount = current_user.transactions.by_category("income").map(&:amount).sum
    @spending_amount = current_user.transactions.spending_transactions.map(&:amount).sum

    @transactions = current_user.transactions.order(sort_column + " " + sort_direction)
    @account = Account.new

    @banks = Bank.all.map{ |bank| bank.name }
    key = params[:bank_name]
    @bank = Bank.find_by_name("#{params[:bank_name]}")
    @searched_banks = Bank.where{name =~ "#{key}%"}
    @selected_bank = Bank.find_by_id(params[:selected_bank_id])

    if params[:search]
      if Account.find(:all, :conditions => ['name LIKE ?', "%#{params[:search]}%"]).first.present?
        @account_name = Account.find(:all, :conditions => ['name LIKE ?', "%#{params[:search]}%"]).first.name
        @transactions = Account.find(:all, :conditions => ['name LIKE ?', "%#{params[:search]}%"]).first.transactions.all
      else
        @account_name = "all accounts"
        @transactions = current_user.transactions.all
      end
    else
      @account_name = "all accounts"
      # @transactions = current_user.transactions.all
    end

    respond_to do |format|
      format.html
      format.json { render :json => @accounts }
      format.js
    end
  end

  def show
    if params[:account]
      @account = Account.find(params[:id])
      @account.update_attributes(params[:account])
    else
      @account = Account.find(params[:id])
    end

    @bank = Bank.find_by_id(@account.bank_id)

    @transactions = current_user.transactions.all

    @accounts = current_user.accounts.all
    @income_amount = current_user.transactions.by_category("income").map(&:amount).sum
    @spending_amount = current_user.transactions.spending_transactions.map(&:amount).sum

    respond_to do |format|
      format.html
      format.js
      format.json { render :json => @account }
    end
  end

  def new
    @title = "Create Account - Budget 24/7"
    @account = Account.new
    @user = current_user

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @account }
    end
  end

  def edit
    @account = Account.find(params[:id])
  end

  def create
    @account = current_user.accounts.build params[:account]

    respond_to do |format|
      if @account.save
        format.html { redirect_to accounts_path, :notice => 'Account was successfully created.' }
        format.json { render :json => @account, :status => :created, :location => @account }
      else
        format.html { render :action => "new" }
        format.json { render :json => @account.errors, :status => :unprocessable_entity }
      end
    end
  end

  def update
    @account = Account.find(params[:id])

    respond_to do |format|
      if @account.update_attributes(params[:account])
        format.html { redirect_to @account, :notice => 'Account was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @account.errors, :status => :unprocessable_entity }
      end
    end
  end

  def destroy
    @account = Account.find(params[:id])
    @account.destroy

    respond_to do |format|
      format.html { redirect_to accounts_url }
      format.json { head :ok }
    end
  end

  def list
    @accounts = current_user.accounts.all
  end

  private

  def sort_column
    Transaction.column_names.include?(params[:sort]) ? params[:sort] : "created_at"
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/views/accounts/_account_item.html.haml
.block.right.tabbed{ class: account.id }
  %h4= account.name

  .totals
    .cash
      = account.transactions.by_category('income').map(&:amount).sum
      %spanTotal cash, $
    .debt
      &ndash;
      = account.transactions.spending_transactions.map(&:amount).sum
      %spanTotal debt, $

  %table.transactions-table
    %thead
      %tr
        %th.date.sort= sortable "created_at", "Date"
        %th.description.sort= sortable "description"
        %th.category.sort= sortable "category"
        %th.amount.sort= sortable "amount"
        %th.edit
    %tbody
      - @transactions.by_account(account).each do |transaction|
        %tr.transaction.edited-item{ class: "item_#{transaction.id}" }
          %td.date
            =l transaction.created_at, format: :short
          %td.description= transaction.description
          %td.category= transaction.category
          %td.amount= transaction.amount
          %td.edit= link_to "Edit", '#', :class => "edit"
        %tr.hidden
          %td{ colspan: 4 }
            = render partial: 'transaction_form', locals: { transaction: transaction, account: transaction.account }

app/views/accounts/_accounts.html.haml
= render 'all_accounts', accounts: @accounts

- @accounts.each do |account|
  = render 'account_item', account: account

app/views/accounts/_accounts_list_menu.html.haml
%menu.left-side
  %ul
    = link_to "Add a new account", '#', :class => "add-account"
    %li
      = link_to "#", class: "all active" do
        All accounts
        %span= pluralize(@accounts.count, 'account')
        %i
    - @accounts.each do |account|
      %li
        = link_to "#", class: account.id do
          = account.name
          %i

app/views/accounts/_all_accounts.html.haml
.block.right.tabbed.all.active
  %h4 All accounts

  .totals
    .cash
      = @income_amount
      %span Total cash, $
    .debt
      &ndash;
      = @spending_amount
      %span Total debt, $

  %table.transactions-table
    %thead
      %tr
        %th.date.sort= sortable "created_at", "Date"
        %th.description.sort= sortable "description"
        %th.category.sort= sortable "category"
        %th.amount.sort= sortable "amount"
        %th.edit
    %tbody
      - @transactions.each do |transaction|
        %tr.transaction.edited-item{ class: "item_#{transaction.id}" }
          %td.date
            =l transaction.created_at, format: :short
          %td.description= transaction.description
          %td.category= transaction.category
          %td.amount= transaction.amount
          %td.edit= link_to 'Edit', '#', class: 'edit'
        %tr.hidden
          %td{colspan: 4}
            = render partial: 'transaction_form', locals: { transaction: transaction, account: transaction.account }

app/views/accounts/_banks_searched_results.html.haml
%h5 Results
%p
  - if @searched_banks.any?
    - @searched_banks.each_with_index do |bank, index|
      .popular-bank
        %span
          = index + 1
          \.
        = link_to bank.name, '#'
        = form_tag accounts_path, method: "get", class: "hidden new-account-form" do
          = text_field_tag :selected_bank_id, bank.id
          = submit_tag "submit"
  - else
    There are no banks

app/views/accounts/_form.html.haml
= form_for(@account) do |f|
  = render 'shared/error_messages', object: f.object

  .field{ style: "display:inline-block;" }
    = f.label :name
    %br
    = f.text_field :name
  &nbsp;&nbsp;&nbsp;
  .field{ style: "display:inline-block;" }
    = f.label :status
    %br
    = f.select :status, Account::ACCOUNT_STATUSES
  &nbsp;&nbsp;&nbsp;
  .field{ style: "display:inline-block;" }
    = f.label :bank
    %br
    = collection_select(:account, :bank_id, Bank.all, :id, :name, {}, { class: "chosen" })
  .actions
    = f.submit

app/views/accounts/_new_account.html.haml
#overlay
.dialog-block
  = link_to "Cancel", '#', class: "dialog-cancel"

  %h3 Add new account
  #dialog-content
    %h5 Find your bank
    %span Enter your bank's name

    .bank-search
      = form_tag accounts_path, method: "get" do
        = text_field_tag :bank_name, params[:bank_name], id: "search-input"
        = submit_tag "Search", id: "search-submit"
        = link_to '#', class: "search-link" do
          %i
      #banks-list-wrapper
        #banks-list= @banks.join(',')
        = link_to "clear bank", '#', :class => 'clear-bank'
    %span
      Examples:
      = link_to "Bank of America", '#'
      ,
      = link_to "FSA Direct Loans", '#'

    #banks
      %h5 Or choose from these popular banks
      - Bank.all.each_with_index do |bank, index|
        .popular-bank
          %span
            = index + 1
            \.
          = link_to bank.name, '#'
          = form_tag accounts_path, method: "get", class: "hidden new-account-form" do
            = text_field_tag :selected_bank_id, bank.id
            = submit_tag "submit"

app/views/accounts/_new_account_final.html.haml
%p
  Account's bank is
  "
  = @selected_bank.name
  "

  = form_for @account, :url => accounts_path do |f|
    .field{ style: "display:inline-block;" }
      = f.label :name
      %br
      = f.text_field :name
    &nbsp;&nbsp;&nbsp;
    .field{ style: "display:inline-block;" }
      = f.label :status
      %br
      = f.select :status, Account::ACCOUNT_STATUSES
    &nbsp;&nbsp;&nbsp;
    .field.hidden
      = f.label :bank
      %br
      = collection_select(:account, :bank_id, Bank.all, :id, :name, { selected: @selected_bank.id }, { class: "chosen" })
    .actions
      = f.submit

app/views/accounts/_transaction_form.html.haml
= form_for account, remote: true do |f|

  = f.fields_for :transactions, transaction do |transactions_fields|
    .date= transactions_fields.text_field :created_at, value: transaction.created_at.strftime('%b %d')
    .description= transactions_fields.text_field :description
    .category= transactions_fields.text_field :category
    .amount= transactions_fields.text_field :amount

    %dl
      %dt Details
      %dd
        You entered this
        = transaction.category
        transaction at
        =l transaction.created_at, format: :short

    %dl.textarea
      %dt= transactions_fields.label :note, "Notes"
      %dd= transactions_fields.text_area :note, rows: 3, cols: 62

    .buttons
      = transactions_fields.submit 'Save'
      = link_to "Cancel", '#', class: "item_#{transaction.id} cancel"

app/views/accounts/edit.html.erb
<h1>Editing account</h1>
<div class="block">
  <div  style="float:right;"><%= link_to "Account edit information", help_create_account_path %></div>

  <%= render 'form' %>

  <%= link_to 'Show', @account %> |
  <%= link_to 'Back', list_accounts_path %>
</div>

app/views/accounts/list.html.erb
<h1>Accounts page</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Status</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

  <% @accounts.each do |account| %>
    <tr>
      <td><%= account.name %></td>
      <td><%= account.status %></td>
      <td><%= link_to 'Show', account %></td>
      <td><%= link_to 'Edit', edit_account_path(account) %></td>
      <td><%= link_to 'Destroy', account, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>
<br />
<%= link_to "New account", new_account_path %>
<br />
<%= link_to "Accounts - Transaction page", accounts_path %>

app/views/accounts/new.html.erb
<h1>New account</h1>

<div class="block">
  <div  style="float:right;"><%= link_to "How can create the Account?", help_create_account_path %></div>

  <%= render 'form' %>

  <%= link_to 'Back', accounts_path %>
</div>

app/views/accounts/show.html.erb
<h1>Account</h1>

<div class="block">
<p>
    <b>Name:</b>
    <%= @account.name %>
  </p>

  <p>
    <b>Status:</b>
    <%= @account.status %>
  </p>

  <p>
    <b>Bank:</b>
    <%= @bank.name %>
  </p>


  <%= link_to 'Edit', edit_account_path(@account) %> |
  <%= link_to 'Back', list_accounts_path %>
</div>

app/views/accounts/show.js.erb
$('#accounts').html("<%= escape_javascript(render :partial => 'accounts') %>");
$('#accounts').customForm();
$('menu.left-side a.active').click();